baseURL = "https://tihu.me"
languageCode = "zh-CN"
title = "醍醐堂記_TihuBlog"
theme = "maupassant"
googleAnalytics = "UA-3430909-2"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

## disqusShortname = "disqus_tihucomment"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "tihu"

[params]
  author = "tihu"
  subtitle = "持续性阅读，碎片化写作。"
  keywords = "tihu,志怪,阅读,笔记体,南北朝"
  description = "tihu,志怪,阅读,笔记体,南北朝"
  busuanzi = true #启用不算子网页统计
  #googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['font-awesome.min.css', 'dark.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['dark.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录



## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

[params.utteranc]
    enable = true
    repo = "tihu/tihu-blog-comment"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-dark" # 样式主题，有github-light和github-dark两种

[params.sequenceDiagrams]
    enable = true
    options = ""            # default: "{theme: 'simple'}"

[params.flowchartDiagrams]
    enable = true
    options = ""

[taxonomies]
    tag = "tags"
    series = "series"
    category = "categories"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "年份"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4